import { Router, type IRouter } from "express";
import healthRouter from "./health";
import patientsRouter from "./patients";
import doctorsRouter from "./doctors";
import appointmentsRouter from "./appointments";
import medicalRecordsRouter from "./medicalRecords";
import prescriptionsRouter from "./prescriptions";
import invoicesRouter from "./invoices";
import dashboardRouter from "./dashboard";
import labRequestsRouter from "./labRequests";
import radiologyRequestsRouter from "./radiologyRequests";
import medicationsRouter from "./medications";
import inventoryRouter from "./inventoryItems";
import departmentsRouter from "./departments";
import staffRouter from "./staff";
import paymentsRouter from "./payments";
import insuranceRouter from "./insuranceRecords";
import whatsappRouter from "./whatsapp";
import bookingsRouter from "./onlineBookings";
import zapierRouter from "./zapier";
import settingsRouter from "./settings";
import adminUsersRouter from "./adminUsers";
import doctorAuthRouter from "./doctorAuth";
import { superAdminRouter } from "./superAdmin";
import authRouter from "./auth";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(patientsRouter);
router.use(doctorsRouter);
router.use(appointmentsRouter);
router.use(medicalRecordsRouter);
router.use(prescriptionsRouter);
router.use(invoicesRouter);
router.use(dashboardRouter);
router.use(labRequestsRouter);
router.use(radiologyRequestsRouter);
router.use(medicationsRouter);
router.use(inventoryRouter);
router.use(departmentsRouter);
router.use(staffRouter);
router.use(paymentsRouter);
router.use(insuranceRouter);
router.use(whatsappRouter);
router.use(bookingsRouter);
router.use(zapierRouter);
router.use(settingsRouter);
router.use(adminUsersRouter);
router.use(doctorAuthRouter);
router.use("/superadmin", superAdminRouter);
router.use(authRouter);

export default router;
